Feature/#3 GPT2Preprocessor 추가
lassl/lassl pull request #10
Opened 2021-11-24 15:54 UTC by iron-ij

- GPT2preprocessor 추가

2021-11-24 15:59 UTC, iron-ij commented
- position ids도 추가 했지만 document에 따라 초기화해주는건 to-do로 남깁니다

2021-11-25 00:46 UTC, bzantium approved these changes
LGTM

2021-11-25 01:55 UTC, seopbo requested changes

2021-11-25 01:55 UTC, seopbo commented on src/preprocessing.py
> +class BaseProcessor:
`BaseProcessor`를 abstract class로 만들고, `RobertaProcessor`, `GPT2Processor`에서 `process` method를 overrding하는 형식이 되면 좋을 것 같습니다.

2021-11-25 01:55 UTC, seopbo commented on src/preprocessing.py
>      def process(self, batch_of_str: List[str]) -> Dict[str, List[int]]:
즉 process method는 abstract method로 지정합니다.

2021-11-25 01:55 UTC, seopbo commented on src/preprocessing.py
>      def process(self, batch_of_str: List[str]) -> Dict[str, List[int]]:
그 이유는 `GPT2Processor`에서 special_tokens_mask는 필요없기 때문입니다.

2021-11-25 08:58 UTC, iron-ij commented on src/preprocessing.py
> +class BaseProcessor:
BaseProcessor를 abstract class 로 변경합니다

2021-11-25 09:07 UTC, iron-ij commented on src/preprocessing.py
>      def process(self, batch_of_str: List[str]) -> Dict[str, List[int]]:
special_tokens_mask 및 tokenizer옵션에서 add_sepecial_token option 삭제 (차이없음 확인)

2021-11-25 14:26 UTC, seopbo requested changes

2021-11-25 14:26 UTC, seopbo commented on src/preprocessing.py
> +                training_example["position_ids"] = [
`position_ids` 관련 로직은 빠지면 어떨까요?

2021-11-25 16:01 UTC, seopbo approved these changes
LGTM

2021-11-25 16:02 UTC, merged