[python] mixed: Support sentence per line type doc
lassl/lassl pull request #20
Opened 2021-11-27 05:49 UTC by seopbo

- line 마다 sentence가 배치된 docu의 serialize를 지원함.
- isort, black 돌림.

Refs: #17

2021-11-27 06:22 UTC, alxiom commented on src/collator.py
> +                )
```suggestion
                token_a = chunk_ids[split_position:]
                token_b = chunk_ids[:split_position]
```

뭔가 black이 강제한 듯 하군요. 제가 보기엔 이게 좀 더 직관적일 듯 합니다~

2021-11-27 06:23 UTC, alxiom commented on src/collator.py
> +                )
```suggestion
                token_a = chunk_ids[:split_position]
                token_b = chunk_ids[split_position:]
```
위와 같은 접근입니다

2021-11-27 06:58 UTC, alxiom commented on src/utils.py
> +        raise NotImplementedError("Implementing loading scripts along your text type.")
```suggestion
        raise NotImplementedError(f"Implementing loading scripts along with your text type (docu, sent), but got {text_type_per_line}")
```
raise 시점에 유저 인풋이 무엇이었는지 보여주면 좋을 것 같습니다~

2021-11-27 07:03 UTC, alxiom commented on src/utils.py
> +    all_file_paths = []
if 분기 안쪽에서 early return이 이뤄지는 것이라면, 여기 있는 `all_file_paths` 변수에  `list_of_file_paths`를 굳이 extend를 하지 않아도 괜찮을 것 같아요

2021-11-27 08:19 UTC, seopbo commented on src/collator.py
> +                )
@alxiom 원 코드가 마치 unpacking 느낌처럼 짜여져 있어서 `black`이 () 쳐준 거같은 느낌ㄴ이네요

2021-11-27 08:24 UTC, seopbo commented on src/utils.py
> +    all_file_paths = []
@alxiom  그러게요 suggestion 기능으로 수정 부탁드립니다 ㅎㅎ

2021-11-28 01:03 UTC, seopbo commented on src/utils.py
> +    all_file_paths = []
@iron-ij

2021-11-28 01:24 UTC, iron-ij requested changes

2021-11-28 01:24 UTC, iron-ij commented on src/utils.py
>          ]
```suggestion
    if text_type_per_line == "docu":
        list_of_file_paths = [
            str(file_path) for file_path in corpora_dir.rglob("*.json")
        ]
```

2021-11-28 01:24 UTC, iron-ij commented on src/utils.py
> +        return load_dataset("json", data_files=all_file_paths, split="train")
```suggestion
        return load_dataset("json", data_files=list_of_file_paths, split="train")
```

2021-11-28 01:24 UTC, iron-ij commented on src/utils.py
> +        all_file_paths.extend(list_of_file_paths)
```suggestion
```

2021-11-28 01:24 UTC, iron-ij commented on src/utils.py
> +            SENTENCE_PER_LINE_SCRIPT, data_files=all_file_paths, split="train"
```suggestion
            SENTENCE_PER_LINE_SCRIPT, data_files=list_of_file_paths, split="train"
```

2021-11-28 01:24 UTC, iron-ij commented on src/utils.py
> +    all_file_paths = []
저도 @alxiom 님과 동일한 의견입니다:), 제가 suggestion 기능 써보겠습니다! 추가로 `docu`와 `sent` 를 체크하는 부분과 json과 txt 파일이 있는지 여부를 확인하는 건 구분하면 좋을 것 같다는 생각이 드네요~!!

2021-11-28 01:33 UTC, seopbo commented on src/utils.py
> +        # sent
```suggestion
```

2021-11-28 02:09 UTC, iron-ij approved these changes

2021-11-28 02:18 UTC, alxiom approved these changes
LGTM

2021-11-28 02:27 UTC, merged