Support adding additional special tokens
lassl/lassl pull request #26
Opened 2021-11-29 13:14 UTC by seopbo

- additional_special_tokens을 subword tokenizer 학습 시 추가하는 기능
- 기본적으로 사용되는 special_tokens와 중복되지않게함.

Refs: #5

2021-11-30 01:40 UTC, bzantium approved these changes
LGTM :)

2021-11-30 04:56 UTC, monologg commented on train_tokenizer.py
> +    "bert-uncased": "bert-base-uncased",
bert-uncased의 경우 default 옵션으로 사용하면 `strip_accents` 로 인해 한국어에 대해서 이슈가 발생할 것 같습니다. 

(https://github.com/huggingface/transformers/blob/6fc38adff272ea3148e05888edf67eeb00170453/src/transformers/models/bert/tokenization_bert.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L406-L411)

이 PR에서 보단 이슈에서 따로 논의하거나 하면 좋을 것 같습니다

2021-11-30 04:57 UTC, monologg approved these changes
LGTM

2021-11-30 05:10 UTC, seopbo commented on train_tokenizer.py
> +    "bert-uncased": "bert-base-uncased",
@monologg 저는 기존의 default가 `do_lower_case=True`이면 `strip_accents=True`인 것으로 이해하고 있습니다. 혹시 이거에 대해서는 한국어 관련해서 어떤 이슈가 있을까요?

2021-11-30 05:28 UTC, monologg commented on train_tokenizer.py
> +    "bert-uncased": "bert-base-uncased",
https://github.com/huggingface/transformers/blob/6fc38adff272ea3148e05888edf67eeb00170453/src/transformers/models/bert/tokenization_bert.py#L419

strip_accent가 안에서 NFD normalize를 해버려 UNK이 처리되는 이슈가 있습니다. 
그래서 `bert-multilingual-base-uncased`가 한국어에서 사용하기 어려웠던 부분이 있었습니다. 
이에 작년에 transformers에서도 strip_accents를 tokenizer_config.json에서 false로 줄 수 있도록 처리되었습니다 (https://github.com/huggingface/transformers/pull/6280)

ref. https://github.com/google-research/bert/pull/228

2021-11-30 05:33 UTC, seopbo commented on train_tokenizer.py
> +    "bert-uncased": "bert-base-uncased",
@monologg default로 `False`인 것을 찾아보거나, 미리 config를 저장해야될 수도 있겠네요.

2021-11-30 09:00 UTC, iron-ij requested changes

2021-11-30 09:00 UTC, iron-ij commented on train_tokenizer.py
> +    additinal_special_tokens: Optional[List[str]] = field(
```suggestion
    additional_special_tokens: Optional[List[str]] = field(
```
오타가 있는 것 같은데 확인 부탁드립니다

2021-11-30 09:03 UTC, iron-ij commented on train_tokenizer.py
> +        )
```suggestion
    if model_args.additional_special_tokens:
        assert len(model_args.additional_special_tokens) == len(
            set(model_args.additional_special_tokens)
        ), "Each additional special tokens must be unique."
        assert not set(tokenizer.all_special_tokens).intersection(
            set(model_args.additional_special_tokens)
        ), "Each additional special tokens are not of default special tokens from tokenizer."

        tokenizer = tokenizer.train_new_from_iterator(
            data_iterator,
            vocab_size=model_args.vocab_size,
            min_frequency=model_args.min_frequency,
            new_special_tokens=model_args.additional_special_tokens,
        )
```

2021-11-30 09:05 UTC, iron-ij commented on train_tokenizer.py
> +        )
제가 보이는대로 suggestion 달아놓긴 했는데, @seopbo 직접 수정하시는게 조금 더 안전할 것 같아요.
로직적인 부분은 따로 코멘트 없습니다. LGTM 👍

2021-11-30 10:23 UTC, merged

2021-12-01 04:44 UTC, monologg commented on train_tokenizer.py
> +    "bert-uncased": "bert-base-uncased",
https://github.com/lassl/lassl/issues/27#issuecomment-983284417