[etc] docs: README 추가
lassl/lassl pull request #39
Opened 2021-12-05 08:00 UTC by bzantium

- README 초안 작성

Refs: #24

2021-12-05 09:03 UTC, monologg requested changes, later dismissed

2021-12-05 09:03 UTC, monologg commented on README.md
> +$ peotry run python3 train_tokenizer.py --corpora_dir $CORPORA_DIR --model_type $MODEL_TYPE --vocab_size $VOCAB_SIZE
```suggestion
$ poetry run python3 train_tokenizer.py --corpora_dir $CORPORA_DIR --model_type $MODEL_TYPE --vocab_size $VOCAB_SIZE
```

2021-12-05 09:03 UTC, monologg commented on README.md
> +        <img alt="Issues" src="https://img.shields.io/github/issues/lassl/lassl">
마이너하긴 한데 색깔을 노란색 말고 다른 것으로 바꿔줘도 좋을 거 같아요! src url을 수정하면 바로 변경 가능할꺼에요:)

2021-12-05 09:51 UTC, seopbo commented on README.md
> +$ peotry run python3 pretrain_language_model.py --config_path $CONFIG_PATH
```suggestion
$ poetry run python3 pretrain_language_model.py --config_path $CONFIG_PATH
```

2021-12-05 09:51 UTC, seopbo commented on README.md
> +$ peotry run python3 serialize_corpora.py --corpora_dir $CORPORA_DIR --tokenizer_dir $TOKENIZER_DIR --model_type --max_length $MAX_LENGTH
```suggestion
$ poetry run python3 serialize_corpora.py --corpora_dir $CORPORA_DIR --tokenizer_dir $TOKENIZER_DIR --model_type --max_length $MAX_LENGTH
```

2021-12-08 04:58 UTC, seopbo requested changes

2021-12-08 04:58 UTC, seopbo commented on README.md
> +$ python3 train_tokenizer.py --corpora_dir $CORPORA_DIR --corpus_type $CORPUS_TYPE --sampling_ratio $SAMPLING_RATIO --model_type $MODEL_TYPE --vocab_size $VOCAB_SIZE --min_frequency $MIN_FREQUENCY
```suggestion
$ python3 train_tokenizer.py --corpora_dir $CORPORA_DIR \
--corpus_type $CORPUS_TYPE \
--sampling_ratio $SAMPLING_RATIO \
--model_type $MODEL_TYPE \
--vocab_size $VOCAB_SIZE \
--min_frequency $MIN_FREQUENCY
```

2021-12-08 04:58 UTC, seopbo commented on README.md
> +$ poetry run python3 train_tokenizer.py --corpora_dir $CORPORA_DIR --corpus_type $CORPUS_TYPE --sampling_ratio $SAMPLING_RATIO --model_type $MODEL_TYPE --vocab_size $VOCAB_SIZE --min_frequency $MIN_F
```suggestion
$ poetry run python3 train_tokenizer.py --corpora_dir $CORPORA_DIR \
--corpus_type $CORPUS_TYPE \
--sampling_ratio $SAMPLING_RATIO \
--model_type $MODEL_TYPE \
--vocab_size $VOCAB_SIZE \
--min_frequency $MIN_FREQUENCY
```

2021-12-08 04:58 UTC, seopbo commented on README.md
> +$ python3 serialize_corpora.py --model_type $MODEL_TYPE --tokenizer_dir $TOKENIZER_DIR --corpora_dir $CORPORA_DIR --corpus_type $CORPUS_TYPE --max_length $MAX_LENGTH --num_proc $NUM_PROC
```suggestion
$ python3 serialize_corpora.py --model_type $MODEL_TYPE \
--tokenizer_dir $TOKENIZER_DIR \
--corpora_dir $CORPORA_DIR \
--corpus_type $CORPUS_TYPE \
--max_length $MAX_LENGTH \
--num_proc $NUM_PROC
```

2021-12-08 04:58 UTC, seopbo commented on README.md
> +$ poetry run python3 serialize_corpora.py --model_type $MODEL_TYPE --tokenizer_dir $TOKENIZER_DIR --corpora_dir $CORPORA_DIR --corpus_type $CORPUS_TYPE --max_length $MAX_LENGTH --num_proc $NUM_PROC
```suggestion
$ poetry run python3 serialize_corpora.py --model_type $MODEL_TYPE \
--tokenizer_dir $TOKENIZER_DIR \
--corpora_dir $CORPORA_DIR \
--corpus_type $CORPUS_TYPE \
--max_length $MAX_LENGTH \
--num_proc $NUM_PROC
```

2021-12-08 05:07 UTC, alxiom approved these changes
저자에 껴주셔서 고맙습니다 ㅠㅠ

2021-12-08 09:31 UTC, iron-ij reviewed
간단한 수정 및 docs example 추가했어요, README 본문에 supported dataset으로 링크만 걸어도 좋겠다는 생각입니다!

2021-12-08 09:31 UTC, iron-ij commented on README.md
> +## environment setting
```suggestion
## Environment setting
```

2021-12-08 11:28 UTC, bzantium commented
> 간단한 수정 및 docs example 추가했어요, README 본문에 supported dataset으로 링크만 걸어도 좋겠다는 생각입니다!

반영하였습니다!

2021-12-08 14:03 UTC, seopbo approved these changes
LGTM

2021-12-08 14:46 UTC, iron-ij approved these changes
LGTM!! 👍 👍 👍

2021-12-08 15:44 UTC, monologg reviewed
@bzantium 
중요한 단어에는 `lassl` 나 **lassl** 형태로 강조해주면 가독성이 좋아질 것 같습니다.
최종 release때 고려해도 늦지 않을 것 같습니다.

2021-12-08 15:44 UTC, monologg commented on README.md
> +</p>
우선은 지워도 괜찮을것 같습니다

2021-12-08 15:53 UTC, monologg commented on README.md
> +언어 모델 사전학습은 크게 1. 토크나이저 학습, 2. 코퍼스 시리얼라이즈, 3. 언어 모델 사전학습의 세 단계로 나눌 수 있습니다. 데이터셋을 지원하는 형식에 맞춰 준비한 뒤 순서에 따라 진행하면 자신만의 사전학습 모델을 만들 수 있습니다. <a href="https://github.com/lassl/lassl/blob/feature/%2324/docs
아래와 같은 느낌으로 바꿔도 나쁘지 않을 것 같습니다

- 언어 모델 사전학습은 크게 **1. 토크나이저 학습**, **2. 코퍼스 시리얼라이즈**, **3. 언어 모델 사전학습**의 세 단계로 나눌 수 있습니다. 
- 데이터셋을 지원하는 형식에 맞춰 준비한 뒤 순서에 따라 진행하면 자신만의 사전학습 모델을 만들 수 있습니다. <a href="https://github.com/lassl/lassl/blob/feature/%2324/docs/supported_dataset.md">지원하는 코퍼스 형태(corpus_type)는 여기서 확인할 수 있습니다.</a>

2021-12-09 02:52 UTC, merged